### ISSUE TITLE
Segmentation fault with HAX_LABEL/LABEL

### ISSUE THREAD

**Issue by BlockOG** [brandtbucher/hax#12]
I have no clue why this happens but here's what's going on:
```py
In [1]: from hax import *
   ...: import dis

In [2]: @hax
   ...: def test():
   ...:     HAX_LABEL("l1")
   ...:     print(0)
   ...:     JUMP_ABSOLUTE("l1")
   ...:

In [3]: dis.dis(test)
  2     >>    0 LOAD_GLOBAL              0 (print)
              2 LOAD_CONST               1 (0)
              4 CALL_FUNCTION            1
              6 POP_TOP
              8 JUMP_ABSOLUTE            0 (to 0)
             10 LOAD_CONST               0 (None)
             12 RETURN_VALUE

In [4]: @hax
   ...: def test():
   ...:     flag = True
   ...:     HAX_LABEL("l1")
   ...:     print(0)
   ...:     JUMP_ABSOLUTE("l1")
   ...:

In [5]: dis.dis(test)
  3           0 LOAD_CONST               1 (True)
              2 STORE_FAST               0 (flag)

  4           4 LOAD_GLOBAL              0 (print)
              6 LOAD_CONST               2 (0)
        >>    8 CALL_FUNCTION            1
             10 POP_TOP
             12 JUMP_ABSOLUTE            4 (to 8)
             14 LOAD_CONST               0 (None)
             16 RETURN_VALUE

In [6]: test()
0
Segmentation fault
```
So if there's a variable defined before it, it for some reason makes the jump absolute go to CALL_FUNCTION instead of LOAD_GLOBAL

**Comment by brandtbucher** [comment]
Interesting! I'll take a look and see if I can figure out why that's happening.

**Comment by brandtbucher** [comment]
Ah, what Python version are you using? I'm guessing it's 3.10?

In 3.10, jump offsets were changed from being measured in bytes (2x the offset) to code units (1x the offset). I never got around to testing HAX on 3.10, so I didn't realize we were still computing jumps the old way. So instead of `JUMP_ABSOLUTE 2 (to 4)`, we're emitting `JUMP_ABSOLUTE 4 (to 8)`.

**Comment by BlockOG** [comment]
Yes, I'm using python 3.10, guess that's why most goto libraries which edit the bytecode had segmentation fault in python 3.10 too

**Comment by brandtbucher** [comment]
3.10 support is in `master`. I'll make a new release when the tests pass.

Thanks for the report!

**Comment by BlockOG** [comment]
Thanks :D
